### ISSUE TITLE
Setup projects through Runme link fails on Windows

### ISSUE THREAD

**Issue by christian-bromann** [stateful/vscode-runme#246]
On Windows, setting up a project through the `vscode://stateful.runme` link fails with

```
Error (FileSystemError): Unable to resolve filesystem provider with relative file path 'C:\Users\CHRIST~1\AppData\Local\Temp\tmp-8536-XAjmNZbIadTK/webdriverio'
	at Yt.c (c:\Users\christianbromann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:26311)
	at Object.createDirectory (c:\Users\christianbromann\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:24679)
	at async e (c:\Users\christianbromann\.vscode\extensions\stateful.runme-0.6.5\out\extension.js:2:2447618)
	at async t.RunmeUriHandler._setupProject (c:\Users\christianbromann\.vscode\extensions\stateful.runme-0.6.5\out\extension.js:2:2445050)
	at async t.RunmeUriHandler.handleUri (c:\Users\christianbromann\.vscode\extensions\stateful.runme-0.6.5\out\extension.js:2:2444661)
```

**Comment by christian-bromann** [comment]
Fixed by https://github.com/stateful/vscode-runme/pull/264
